# Generated by Django 5.1.5 on 2025-01-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='department_id',
            field=models.ManyToManyField(blank=True, to='api.department'),
        ),
    ]
